### ISSUE TITLE
Bug with attribute named `attributes`

### ISSUE THREAD

**Issue by zxqfox** [ozum/sequelize-pg-generator#14]
Atm if I use this name sequelize will fall with exception:
```
     TypeError: Cannot read property 'attributes' of undefined
      at [object Object].Instance.set (node_modules/sequelize/lib/instance.js:305:38)
      at [object Object].funcs.(anonymous function) (node_modules/sequelize/lib/model.js:769:23)
      at [object Object].Model.refreshAttributes (node_modules/sequelize/lib/model.js:935:38)
      at [object Object].Model.init (node_modules/sequelize/lib/model.js:720:8)
      at [object Object].Sequelize.define (node_modules/sequelize/lib/sequelize.js:578:17)
      at defineModel (model/index.js:37:35)
...
```

Should we rename `attributes` to something safe?

**Comment by ozum** [comment]
What is the reason of this failure, could you please explain more?

**Comment by zxqfox** [comment]
Field named `attributes` ;-)
```js
module.exports = {
    modelName: "someModel",
    options: {
        tableName: "some_model",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.INTEGER,
            field: "id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "some_model_pkey"
        },
        "attributes": {
            type: Seq.JSONB,
            field: "attributes"
        },
    },
    relations: []
};
```

**Comment by zxqfox** [comment]
I'm not sure if we should rename it here. But depends on https://github.com/sequelize/sequelize/issues/4610 — better to rename if maintainers of sequelize will decide to throw an error.

**Comment by ozum** [comment]
I think it is not related to sequelize-pg-generator until sequelize authors decide to change it, because this exception is thrown by sequelize.

**Comment by zxqfox** [comment]
Okay, let's wait for sequelize maintainers. Closing for now as non-constructive.
