### ISSUE TITLE
Column not marked with primaryKey

### ISSUE THREAD

**Issue by egeste** [ozum/sequelize-pg-generator#9]
Hey @ozum - thanks for this project - it's really nice. I'm having the following problem, however.

After creating a table and subsequently enhancing it with an _id column, marked as primaryKey as follows:

```coffeescript
module.exports =

  up: (queryInterface, Sequelize) ->
    addColumns = {

      _id:
        type: Sequelize.INTEGER
        unique: true
        allowNull: false
        primaryKey: true
        autoIncrement: true

      _uuid:
        type: Sequelize.UUID
        unique: true
        allowNull: false
        primaryKey: true
        defaultValue: Sequelize.UUIDV4()

    }

    promises = []
    for table in TABLES
      for column, columnSpec of addColumns
        promises.push queryInterface.addColumn table, column, columnSpec
    return Bluebird.join promises...

  down: (queryInterface, Sequelize) ->
    promises = []
    for table in TABLES
      for column in ['_id', '_uuid']
        promises.push queryInterface.removeColumn table, column
    return Bluebird.join promises...
```

I generate my models with `spgen -d database -u user -p pass -o src/autogen-models -t sequelize4`

and subsequently attempt to export my ORM as such:

```coffeescript
path = require 'path'
database = require path.join __dirname, 'autogen-models'

module.exports = (options) ->
  db = options[options.environment]
  database.setup db.database, db.username, db.password, {
    host: db.host
    port: db.port
  }
  return database
```

which in turn produces:
```
> $ node ./index.js                                                                                                                                                                        (💎ruby-2.2.1)(⬡0.12.4)
/home/egeste/Source/project_name/db/node_modules/sequelize/lib/model.js:167
      throw new Error("A column called 'id' was added to the attributes of '"
            ^
Error: A column called 'id' was added to the attributes of 'Action' but not marked with 'primaryKey: true'
  at [object Object].addDefaultAttributes (/home/egeste/Source/project_name/db/node_modules/sequelize/lib/model.js:167:13)
  at [object Object].Model.init (/home/egeste/Source/project_name/db/node_modules/sequelize/lib/model.js:711:24)
  at [object Object].Sequelize.define (/home/egeste/Source/project_name/db/node_modules/sequelize/lib/sequelize.js:552:17)
  at defineModel (/home/egeste/Source/project_name/db/src/autogen-models/index.js:35:35)
  at Array.forEach (native)
  at init (/home/egeste/Source/project_name/db/src/autogen-models/index.js:119:29)
  at Object.module.exports.setup (/home/egeste/Source/project_name/db/src/autogen-models/index.js:153:5)
  at module.exports (/home/egeste/Source/project_name/db/src/index.coffee:6:12)
  at Object.<anonymous> (/home/egeste/Source/project_name/db/index.js:9:18)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

What gives?

**Comment by egeste** [comment]
After debugging the issue a little, it appears that this is actually a bug in pg-structure (which, thankfully, you also own). More interestingly, it appears to be related to the fact that determining which columns are a primaryKey in postgresql is exceptionally difficult.

**Comment by egeste** [comment]
More interesting observations, according to the PostgreSQL documentation on Primary Keys:

`Technically, a primary key constraint is simply a combination of a unique constraint and a not-null constraint.`
http://www.postgresql.org/docs/9.0/static/ddl-constraints.html#AEN2494

So a potential workaround may be to check the state of unique and default on a column.

```javascript
Column.prototype.isPrimaryKey = function () {
    return (this.unique() !== null && this.default() !== null);
}
```

**Comment by egeste** [comment]
Closing as a duplicate of https://github.com/ozum/pg-structure/issues/2
